flowchart BT

A[Scientific Foundations]
B[Combat Athlete Model]
C[Decision-Making Engine]
D[Exercise Selection]
E[Recommendations]
F[CAS<br/>Explainable Decision System]

A --> B
B --> C
C --> D
D --> E
E --> F